# Temporary status
- name: "🗯️ Waiting for feedback"
  color: "aadefa"
  description: ""
- name: "🔴 Blocked"
  color: "ff3f14"
  description: "Blocked by another issue or pull request"
- name: "🔒 After next release"
  color: "e8f274"
  description: "Will be done after the next release"

# Final status
- name: "⚰️ Inactive"
  color: "000000"
  description: "No answer was received for weeks"
- name: "👥 Duplicate"
  color: "524f4f"
  description: "Issue duplicates an existing issue"

# Priority
- name: "🚨 Urgent"
  color: "d5232f"
  description: ""
- name: "💤 Low priority"
  color: "4285f4"
  description: ""

# Complexity
- name: "☣️ Hard to do"
  color: "7d0008"
  description: ""
- name: "🟩 Easy to do"
  color: "34cf43"
  description: ""

# Issue category
- name: "Config problem"
  color: "ffc7ea"
  description: ""
- name: "Shoutrrr"
  color: "ffc7ea"
  description: ""
- name: "Provider update"
  color: "ffc7ea"
  description: ""
- name: "IP fetching"
  color: "ffc7ea"
  description: ""
- name: "Database"
  color: "ffc7ea"
  description: ""
- name: "New provider"
  color: "ffc7ea"
  description: ""
